### ISSUE TITLE
[hebrew/block] Why is only v sound and vet name shown for U-BET?

### ISSUE THREAD

**Issue by bdenckla** [r12a/scripts#154]
[source] https://r12a.github.io/scripts/hebrew/block

![image](https://user-images.githubusercontent.com/941315/231818907-3a0597e0-702b-4e73-8a5b-065852463e90.png)

Below, both v and b sounds are shown, so I'm puzzled as to why the b sound and the bet name are not shown above.

Whereas, correctly, both v and b sounds are shown below:

![image](https://user-images.githubusercontent.com/941315/231819017-74a97334-9331-41ed-bb3f-601e0eb3ff56.png)

There's an asymmetry running in the other direction in the final section, since only a *bet* example is given, I fear implying that somehow *vet* can't exist in vowelled text (or at least confusing the reader on this point):

![image](https://user-images.githubusercontent.com/941315/231819534-4e8e3b71-6d29-4b1e-a8ba-de343d389aa6.png)

An actual pointed example word using *vet* isn't needed, perhaps. Perhaps instead of saying:

> In vowelled text, written [...]

It could be clarified by saying

> In vowelled text, the b-sounding (*bet*) form is written [...]

Or maybe just somehow the layout (e.g. indentation) could make it clearer that this explanation about vowelled text applies only the b-form.

![image](https://user-images.githubusercontent.com/941315/231820401-04634e3c-bf39-45d5-87e5-ec1945e85eaa.png)

**Comment by bdenckla** [comment]
Same question for U-PE, namely, why is only f sound and fe name shown for it?

![image](https://user-images.githubusercontent.com/941315/231829077-9e8f7162-27f1-4d00-acb3-b27ea5ba6d0f.png)

Perhaps these two issues are really the same underlying issue described in #150.

**Comment by r12a** [comment]
Mostly fixed by https://github.com/r12a/scripts/issues/150

Added some wording to indicate that 05BC use relates to the b sound.

**Comment by bdenckla** [comment]
I now see the b as well as the v sound shown ("v b" in the image below, not just "v" as it used to be). Great. But I still only the vet name, i.e. the bet name is still not shown:

![image](https://user-images.githubusercontent.com/941315/232293796-a70ebaaa-14e5-42cd-925a-a0e2e06cb9c2.png)

But perhaps you still plan to fix that since this issue is still open and above you say that this is only "mostly" fixed.

**Comment by r12a** [comment]
That should be fixed by the database merge i just did.

**Comment by bdenckla** [comment]
Great, now at https://r12a.github.io/scripts/hebr/block.html#char05D1 I see the bet name mentioned:

![image](https://user-images.githubusercontent.com/941315/232300159-a8f66ac2-564e-490b-8391-785cf20c5475.png)

and I also see the small but rather critical "b is" qualification added, changing

> In vowelled text, written

to

> In vowelled text, b is written

**Comment by bdenckla** [comment]
And I see the analogous fixes/improvements to _pe_, e.g. at https://r12a.github.io/scripts/hebr/block.html#char05E4 I see:

![image](https://user-images.githubusercontent.com/941315/232300859-ed3c13d7-f488-4956-8f45-2fffb63b41d7.png)

I'm a little confused about how any of those Hebrew spellings correspond to the dipthong pronunciations (pej/fej), but I am not, personally, too concerned with that information (though others may be). To me, neither the _alef_ nor the _he_ spellings could be interpreted as indicating the "ej" dipthong. I thought _yod_ spellings were used for that.
